// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYB51p1rSumFoCovBYyUStqp-dUdqY9xs',
    appId: '1:408552959870:web:e2da94a8fb3ecd53cf4d2f',
    messagingSenderId: '408552959870',
    projectId: 'csci410-bookapp',
    authDomain: 'csci410-bookapp.firebaseapp.com',
    storageBucket: 'csci410-bookapp.firebasestorage.app',
    measurementId: 'G-K64MJ2MD83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGCwQDscHDvp0YFkn02nAYq9tkKg6ML4',
    appId: '1:408552959870:android:4588746523bef4becf4d2f',
    messagingSenderId: '408552959870',
    projectId: 'csci410-bookapp',
    storageBucket: 'csci410-bookapp.firebasestorage.app',
  );
}
